inherit_from: .rubocop_todo.yml

require: rubocop-rspec

inherit_gem:
  bixby: bixby_default.yml

Rails:
  Enabled: true

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Include:
    - '**/Capfile'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/config.ru'
    - 'marc_to_solr/translation_maps/*.rb.tmpl'
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/deploy.rb'
    - 'config/initializers/*'
    - 'vendor/**/*'

Style/BlockDelimiters:
  Exclude:
    - 'spec/models/jsonld_record_spec.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Style/NumericPredicate:
  Enabled: false  
    
Naming/AccessorMethodName:
  Exclude:
    - 'app/models/concerns/scsb_partner_updates.rb'
    - 'marc_to_solr/lib/princeton_marc.rb'
