default: &default
  bibs_read_only: <%= ENV['ALMA_BIBS_READ_ONLY'] %>
  region: <%= ENV['ALMA_REGION'] %>

development:
  <<: *default

test:
  <<: *default
  bibs_read_only: 'TESTME'
  region: 'ALMA'

production:
  <<: *default
