development:
  adapter: postgresql
  encoding: unicode
  database: marc_liberation_dev
  pool: 5
  timeout: 5000
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: marc_liberation_test
  pool: 5
  timeout: 5000
  host: 127.0.0.1

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['BIBDATA_DB'] %>
  pool: 20
  username: <%= ENV['BIBDATA_DB_USERNAME'] %>
  password: <%= ENV['BIBDATA_DB_PASSWORD'] %>
  timeout: 5000
  host: <%= ENV['BIBDATA_DB_HOST'] %>
